# Predicción del precio de automóviles
Base de datos de [Rehan Liaqat en Kaggle](https://www.kaggle.com/datasets/rehan497/car-price-prediction-dataset)

Análisis por Luis Gerardo Ramirez Archundia | 🇲🇽

---

# Sobre la base de datos
(Extraído del repositorio original)
 
Este conjunto de datos contiene registros estructurados y orientados al consumidor de automóviles individuales que figuran en el mercado. Cada fila corresponde a un solo vehículo e incluye especificaciones técnicas, indicadores de uso y un precio de mercado. La colección está diseñada para ser clara, estar bien etiquetada y ser inmediatamente útil para el análisis exploratorio de datos, la ingeniería de características y el aprendizaje supervisado.Este conjunto de datos proporciona información detallada sobre varios modelos de automóviles y sus precios de mercado. Incluye características como la marca, el modelo, las especificaciones del motor, el tipo de combustible, el kilometraje y el tipo de transmisión, lo que lo hace ideal para la predicción de precios de automóviles, el análisis exploratorio de datos (EDA) y los proyectos de aprendizaje automático.

## Utilidad de esta base de datos
- Directamente accionable — las características son variables del mundo real comúnmente utilizadas en modelos de precios y valoración.

- Compacto y enfocado — conjunto de características corto y de alta relevancia que reduce la carga de preprocesamiento.

- Versátil — admite tareas que van desde el análisis descriptivo y la visualización hasta la regresión (predicción de precios) y la clasificación (condición, tipo de combustible).

- Ideal para demostraciones y enseñanza — lo suficientemente pequeño para realizar iteraciones rápidas, pero lo bastante rico para permitir comparaciones significativas entre modelos.

## Atributos
- `Car ID`: Identificador único para cada vehículo.  
- `Brand`: Fabricante (por ejemplo, Tesla, BMW, Toyota).  
- `Model`: Nombre específico del modelo.  
- `Year`: Año de fabricación o modelo.  
- `Engine Size`: Cilindrada del motor (en litros o cc).  
- `Fuel Type`: Tipo de combustible — Gasolina, Diésel, Eléctrico, Híbrido, etc.  
- `Transmission`: Tipo de transmisión — Manual o Automática.  
- `Mileage`: Distancia total recorrida (en km o millas).  
- `Condition`: Estado categórico — Nuevo, Usado, Excelente, Regular.  
- `Price`: Precio de venta o de mercado listado (variable objetivo).  

---

# Librerías
En esta sección se importarán las librerías necesarias paraeste proyecto.

In [64]:
# librerías básicas
import pandas as pd
import numpy as np
import os
import sys


# visualización
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# scikit-learn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
# random_seed
seed=14

# tensorflow
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau, TensorBoard
import datetime

# versiones utilizadas
print(f'Versión de Python {sys.version}')
print(f'Versión de Pandas {pd.__version__}')
print(f'Versión de Numpy {np.__version__}')
print(f'Version de Tensorflow {tf.__version__}')

Versión de Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:15:57) [MSC v.1916 64 bit (AMD64)]
Versión de Pandas 2.3.2
Versión de Numpy 1.26.4
Version de Tensorflow 2.10.0

# Datos

In [65]:
df=pd.read_csv('data/car_price_prediction_.csv')
print('Los datos fueron importados correctamente!')
# motramos parte de los datos
df.head(5)

Los datos fueron importados correctamente!

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,2,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,3,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,4,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,5,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang

In [66]:
# infomración general de los datos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car ID        2500 non-null   int64
 1   Brand         2500 non-null   object
 2   Year          2500 non-null   int64
 3   Engine Size   2500 non-null   float64
 4   Fuel Type     2500 non-null   object
 5   Transmission  2500 non-null   object
 6   Mileage       2500 non-null   int64
 7   Condition     2500 non-null   object
 8   Price         2500 non-null   float64
 9   Model         2500 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 195.4+ KB

In [67]:
# verificamos la existencia de datos nulos
print('Existencia de datos tipo NULL\n')
null_data=df.isnull().sum()
print(null_data)
if null_data.sum()==0:
    print('-----\nNo existen datos tipo NULL')
else:
    print('Se ecnontraron datos tipo NULL')

Existencia de datos tipo NULL

Car ID          0
Brand           0
Year            0
Engine Size     0
Fuel Type       0
Transmission    0
Mileage         0
Condition       0
Price           0
Model           0
dtype: int64
-----
No existen datos tipo NULL

---

In [68]:
df.drop(columns=['Car ID'])

,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang
...,...,...,...,...,...,...,...,...,...
2495,Audi,2020,2.4,Petrol,Automatic,22650,Like New,61384.10,Q5
2496,Audi,2001,5.7,Hybrid,Manual,77701,Like New,24710.35,A3
2497,Ford,2021,1.1,Hybrid,Manual,272827,Like New,29902.45,Fiesta
2498,Audi,2002,4.5,Diesel,Manual,229164,Like New,46085.67,Q5
2499,Toyota,2005,4.6,Diesel,Automatic,80978,Used,16594.14,RAV4

Hay algunas inconsistencias con esta base de datos:
- Autos eléctricos tienen capacidad del motor
- Autos nuevos tienen kilometraje
- Autos electricos tienen trnasmisión manual
- Autos eléctricos usan combustible

---

# Preparación de los datos

In [69]:
'''
    Para este estudio no es necesaria la columna que contiene el ID
    de cada vehículo, por lo que es la omitiremos.
'''
df=df.drop(columns=['Car ID'])

'''
    Algunos de los nombres de las columnas contienen espacios y 
    letras mayúsculas, para evitar complicaciones en el tratamiento
    uniremos las palabras por guiones bajos y todo en minúsculas.
'''
df.columns=df.columns.str.replace(' ', '_')
df.columns=df.columns.str.lower()

print(df.columns)

Index(['brand', 'year', 'engine_size', 'fuel_type', 'transmission', 'mileage',
       'condition', 'price', 'model'],
      dtype='object')

## Inconsistencias de los datos
Algunos datos en la tabla presentan incositencias, por ejemplo: Tesla fabrica autos eléctricos y notamos la existencia de registros donde se consideran autos con distintos tipos de combustibe, capacidad del motor y tipo de transmisión.

De manera similar, autos clasificados como nuevos tienen kilometraje recorrido.

In [70]:
# pasamos a tipo eléctrico los autos Tesla
df.loc[df['brand']=='Tesla', 'fuel_type']='Electric'
# cambiamos la capacidad del motor a pd.Na
df.loc[df['brand']=='Tesla', 'engine_size']=np.nan
# cambiamos el tipo de transmisión a automática a todos los Tesla
df.loc[df['brand']=='Tesla', 'transmission']='Automatic'
# en autos electricos no existen las transmisiones manuales
df.loc[df['fuel_type']=='Electric', 'transmission']='Automatic'
# para autos nuevos el kilometraje debe ser cero
df.loc[df['condition']=='New', 'mileage']=0
df.head(5)

,brand,year,engine_size,fuel_type,transmission,mileage,condition,price,model
0,Tesla,2016,NaN,Electric,Automatic,0,New,26613.92,Model X
1,BMW,2018,4.4,Electric,Automatic,143190,Used,14679.61,5 Series
2,Audi,2013,4.5,Electric,Automatic,0,New,44402.61,A4
3,Tesla,2011,NaN,Electric,Automatic,0,New,86374.33,Model Y
4,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang

In [71]:
# obtenemos las columnas que contienen datos tipo object
object_columns=[]
for i in df.columns:
    if df[i].dtypes=='O':
        object_columns.append(i)
print(object_columns)

['brand', 'fuel_type', 'transmission', 'condition', 'model']

# Análisis exploratorio

In [109]:
for col in ['fuel_type', 'transmission', 'condition']:
    data=(
        df.groupby(['brand', col]).size().reset_index(name='count')
    )
    
    fig=px.bar(data, x='brand', y='count', color=col, barmode='group', title=col, text_auto=True)
    fig.show()

In [86]:
list=df[['brand', 'fuel_type']].value_counts().reset_index()

px.bar(list, x='brand', y='count', color='fuel_type', barmode='group')

In [108]:
data=df[['brand', 'year']]
px.bar(data.value_counts().reset_index(), 
        x='year', 
        y='count', 
        color='brand', 
        barmode='relative',
        title='Conteo de modelos de autos por marca')

In [138]:
df.query('brand == "Ford" and model == "Mustang"')

,brand,year,engine_size,fuel_type,transmission,mileage,condition,price,model
4,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang
11,Ford,2017,5.7,Electric,Automatic,169737,Used,28074.19,Mustang
15,Ford,2010,3.9,Electric,Automatic,240904,Used,21796.16,Mustang
34,Ford,2005,5.6,Petrol,Automatic,252862,Like New,22849.55,Mustang
51,Ford,2016,2.1,Hybrid,Automatic,139728,Used,39212.51,Mustang
...,...,...,...,...,...,...,...,...,...
2296,Ford,2015,3.6,Electric,Automatic,286608,Like New,27508.67,Mustang
2338,Ford,2019,5.8,Diesel,Manual,215888,Like New,46862.09,Mustang
2343,Ford,2011,2.4,Hybrid,Manual,42311,Used,89602.36,Mustang
2386,Ford,2010,4.5,Electric,Automatic,61086,Like New,22347.13,Mustang
2432,Ford,2021,3.6,Petrol,Manual,0,New,90352.33,Mustang

In [129]:
brand=df['brand']=='Audi'
model=df['model']=='A4'
year=df['year']==2008

df.loc[model, year]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).